server:
  port: 8084

spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: host.docker.internal:9092
    consumer:
      group-id: notif-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

management:
  endpoints:
    web:
      exposure:
        include: "*"
