server:
  port: 8081
spring:
  application:
    name: product-service
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27018/product_db?authSource=admin

springdoc:
  swagger-ui:
    path: "/swagger-ui.html"
  api-docs:
    path: "/api-docs"

management:
  endpoints:
    web :
      exposure :
        include: "*"
  metrics:
    distribution:
      percentile-histogram:
        http :
          server :
            requests: true
  tracing:
    sampling:
      probability: 1.0
  observations :
    key-value :
      application : product-service