server:
  port: 8082

spring:
  application:
    name: inventory-service
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  datasource:
    url: jdbc:mysql://localhost:3308/inventory_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  swagger-ui:
    paths: "/swagger-ui.html"
  api-docs:
    paths: "/api-docs"

management:
  endpoints:
    web :
      exposure :
        include: "*"
  metrics:
    distribution:
      percentile-histogram:
        http :
          server :
            requests: true
  tracing:
    sampling:
      probability: 1.0
  observations :
    key-value :
      application : inventory-service